### ISSUE TITLE
12월 2일(목) - 12월 5일(일)

### ISSUE THREAD

**Issue by sangmandu** [boostcampaitech2/final-project-level3-nlp-04#2]
## Task
> 2호선 Pilot 끝내기
* 우창, 신곤
* [x] 2호선 전체 크롤링 데이터
* [ ] 중복 유부 확인하면서 크롤링
> DB 연동
* 희락, 세진
* [ ] 크롤링 데이터를 디비로 관리
* [ ] 버전관리
* [ ] 중복제거
> 모델링
* 상민, 상준
* [x] KoGPT-SKT output
* [x] KoGPT-Kakao setting

## 파일럿 결과 이후 관찰할 것
1. 전체리뷰의 별점분포
2. 사진리뷰의 별점분포
3. 1점과 3점의 리뷰 내용
4. 2점과 4점을 어떻게할지
5. 배달평점이 없었을 때의 분포
