### ISSUE TITLE
Modeling : Review Generation & Star Classification

### ISSUE THREAD

**Issue by sangmandu** [boostcampaitech2/final-project-level3-nlp-04#5]
## 작성 규칙
- 금일 계획 수행
- 회고
- 금일 결과 작성 및 분석
- 익일 계획 수립

## 주간 목표
- [x] 리뷰 생성 모델 : input format 평가
- [ ] 리뷰 생성 모델 : 카카오 GPT
- [ ] 리뷰 생성 모델 : GPT Trinity
- [ ] 메뉴 구분 모델
- [ ] 별점 분류 모델 : KLUE/Roberta
  - Pretraning
  - Finetuning
- [ ] 별점 분류 모델 : KoElectra
  - Pretraning
  - Finetuning

### Task
총 정리
1. 메뉴 구분 모델은 고난이도 태깅 작업과 가이드라인이 필요하므로 시간상 하지 않기로 했다.
2. 리뷰 생성 모델은 GPT-2와 GPT-2 Trinity로 결정. 카카오 GPT는 너무 커서 학습이 되지 못한다.
3. 별점 태깅 1만개가 끝났으며, 별점 분류 모델로 KLUE/Roberta-Large는 77점, KoElectra-v3는 75점을 달성했다. 추후에, hold out 방식으로 valid점수가 낮은 1~2인의 점수를 수정하려고 한다.

### Task
- [x] 메뉴 구분 모델
- [x] 리뷰 생성 모델

### Task
- [x] 메뉴 구분 모델

### Task
> - [x] 별점 분류 모델
- 리뷰를 받으면, 맛점수와 배달점수로 나누어서 output
- KoElectra => pretraining & finetuning

> - [x] 메뉴 구분 모델
- ?

> - [x] 리뷰 생성 모델 
- ?

### Task
> - [x] 카카오 GPT
- 세팅
- 200epoch
- 파일럿 데이터
- 방법 1, 3 

> - [x] GPT-2 Trinity
- 세팅
- 200epoch
- 파일럿 데이터
- 방법 1, 3 

> - [x] 리뷰 생성 모델
- 200epoch
- 파일럿 데이터
- 방법 1, 3 

> - [x] 별점 분류 모델
- 리뷰를 받으면, 맛점수와 배달점수로 나누어서 output
- KLUE/RoBerta => pretraining & finetuning

### 결론
추후에 모델을 학습하고 나서 방법1과 방법3을 다시 적용해보도록 한다.

### 회고
![image](https://user-images.githubusercontent.com/85214907/144847691-640a9478-f529-44e2-ade8-381bca8ac68d.png)
![image](https://user-images.githubusercontent.com/85214907/144847870-58f07068-4c8b-43a3-923a-ea329afced41.png)
* 샤브샤브는 데이터에 없는 음식이다 보니 리뷰를 생성할 때, 최대한 샤브샤브를 지양하고 내뱉는 모습이다. 5점 리뷰중에 특정 음식에 대한 언급이 없는 리뷰가 많아서 가능한 것으로 보인다. 반면에 1점 리뷰의 경우에는 대부분 특정 음식을 언급하기 때문에 샤브샤브인데도 다른 음식에 대한 리뷰로 섞여나오는 것으로 보인다.

![image](https://user-images.githubusercontent.com/45033215/144842122-3ef63e18-7e67-4168-ae95-ba701550cf73.png)
* 문장이 좀 더 길어야 될 것 같음. 또한 epoch 50번을 한다고 모델이 잘 학습하는 것은 아닌 것 같음. epoch를 좀 더 길게해보자.

![image](https://user-images.githubusercontent.com/45033215/144842182-ae5d1e6d-cbf0-45ed-8174-b7cf0c8cd065.png)
* 찌개에 대해 상당히 구체적인 리뷰라서 놀랐음. 다만, 길이가 길수록 굉장히 특정 경험적인 리뷰가 생성되어서 너무 긴 글자수 역시 제한을 해야하나 싶은 고민이 들었음

### Task

> SKT-GPT Finetuning 발전
- [x] 점수 종합하기
> 종합 (상민 + 상준)

모델 1 : 80 + 89 = 169
모델 2 : 72 + 78 = 150
모델 3 : 86 + 86 = 172
모델 4 : 82 + 84 = 166

> 상민

2 3 3 2 10
3 3 2 2 10
3 3 2 4 12
2 2 2 2 8

4 4 2 4 14
4 3 3 3 13
4 3 4 4 15
4 3 3 3 13

3 3 2 1 9
1 1 3 3 8
3 3 3 2 11
3 4 1 3 11

1 1 1 3 6
1 1 1 1 4
1 1 1 1 4
2 1 3 1 7

4 1 4 4 13
1 3 3 3 10
4 3 3 3 13
3 4 1 4 12

1 1 4 4 10
1 1 1 4 7
4 4 4 1 13
4 1 4 3 12

3 1 1 1 5
3 3 3 3 12
3 3 3 3 12
1 3 4 3 11

1 4 4 4 13
1 1 3 3 8
1 3 1 1 6
1 1 3 3 8

> 상준

1-1 : 2/3/3/2 10
1-2 : 3/3/2/2 10
1-3 : 3/3/2/4 12
1-4 : 2/2/2/2 8

2-1 : 4/4/2/4 14
2-2 : 4/3/3/3 13
2-3 : 4/3/4/4 15
2-4 : 4/3/4/3 14

3-1 : 4/4/1/4 13
3-2 : 2/1/3/2 8
3-3 : 3/1/4/1 9
3-4 : 3/4/2/3 12

4-1 : 2/2/2/4 10
4-2 : 2/1/2/2 7
4-3 : 2/3/1/2 8
4-4 : 2/2/4/1 9

5-1 : 4/1/4/4 12
5-2 : 1/3/3/3 10
5-3 : 4/3/3/3 13
5-4 : 3/4/1/4 12

6-1 : 2/2/4/4 12
6-2 : 1/1/1/4 7
6-3 : 4/4/4/1 13
6-4 : 4/1/4/3 12

7-1 : 3/1/2/2 8
7-2 : 3/3/3/3 12
7-3 : 3/3/2/2 10
7-4 : 4/3/1/3 11

8-1 : 1/1/4/4 10
8-2 : 2/2/3/4 11
8-3 : 2/1/1/2 6
8-4 : 1/1/3/1 6

- [x] 문장 평가하기
- 별점 기준과 문장 선별 기준은 Week 1 참조

#### 있는 가게와 있는 메뉴
> 직화신불닭&국물닭발-강북, 찜, 5점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144847289-8ad1b16f-a896-49c2-9845-927214c443a5.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144847364-707f0c8b-a495-42de-ab5d-824d6f99ea53.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847266-df9107bd-5584-4a5a-9a38-1ffcb74c0b3e.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851651-0091701a-d54c-45bd-9f3e-d86e024711a6.png)

> BBQ-대구수성점, 치킨, 1점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144847562-4b0615d8-8f17-433b-8e5d-586b07f483b9.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144847632-5851a9c6-4f7c-47cb-a17a-9dfec04a4a91.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847305-385572ee-ddea-4d25-9ecc-b0659bb0a783.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144853997-0dd4cae0-9a5a-4d61-b353-d3154aab9e0e.png)

#### 있는 가게와 없는 메뉴
야미가-대구경북대점, 샤브샤브, 5점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144847691-640a9478-f529-44e2-ade8-381bca8ac68d.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144847746-7e1a0cc9-0489-42f8-864a-58432b9def78.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847363-70828ab8-7450-470f-8d08-449da2d19be3.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851753-d7e1cb24-ba61-42e4-a7f9-3be0b6888d49.png)

선녀와나무꾼한식분식, 간장게장, 1점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144847870-58f07068-4c8b-43a3-923a-ea329afced41.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144847975-fa695d94-7b2b-415a-8e4d-636f99f1cff8.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847438-fb11c5f4-6809-4570-9956-73f4739ec2ea.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851781-412a4d65-59fd-4210-9f30-0952f648ca5c.png)

#### 없는 가게(메뉴 유추 가능)와 있는 메뉴
> 원조상준분식, 김밥, 5점
* 방법 1 
* ![image](https://user-images.githubusercontent.com/85214907/144848119-a97c0470-85be-41d7-9e1b-9814844a9d7a.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144848487-a580a360-5f0a-4ada-921f-2b5ffe45aeb3.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847542-2904544b-ab15-4d12-96de-bfa73c0b9de5.png)
* 방법 4
![image](https://user-images.githubusercontent.com/45033215/144851820-0e6df197-82e1-4ff3-ab15-7c2d63ceebb7.png)

> 고급상민한식당, 찌개, 1점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144848586-70588470-ffee-4cdb-a700-68d027523106.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144848726-375ac628-f1b3-4e10-a03c-68d8b83555bf.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847563-08c9afde-252b-42ff-9e0b-ddb326f57873.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851848-143b8d6c-e10b-4f19-9854-e06cc84dc15f.png)

#### 없는 가게(메뉴 유추 불가)와 없는 메뉴
> 상상플러스, 랍스타, 5점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144848863-edd31d63-49f8-4aee-b97f-9e55cf147e4f.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144848918-a0e93e98-87d1-4e31-952b-3c10eddf7d09.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847689-7a78af07-4111-4e14-b8b8-9136ca044daf.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851869-97df862d-ae06-4431-8667-2da06f1084c0.png)

> 핫식스, 버섯전골, 1점
* 방법 1 
![image](https://user-images.githubusercontent.com/85214907/144849086-cadd0a2b-509f-4d5d-8748-1f730f91e0ac.png)
* 방법 2 
![image](https://user-images.githubusercontent.com/85214907/144849231-700b3cec-5f27-427e-88a0-72c296972c3d.png)
* 방법 3 
![image](https://user-images.githubusercontent.com/45033215/144847723-b1f24b7c-814f-4ea6-a2cb-58a404dd5c72.png)
* 방법 4 
![image](https://user-images.githubusercontent.com/45033215/144851911-87155495-7bb8-466e-894e-cbc776ae66bd.png)

###  Timeline
4시 시작
