### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by raki-1203** [boostcampaitech2/final-project-level3-nlp-04#7]
# TODO List
* 희락, 세진, 재영
- [x] DB 테스트
- [x] 일일 크롤링 코드 추가 + 자동화
- [x] 전처리 추가 + 자동화
- [ ] 일별 Task 계획 세우기
- [ ] 주별 Task 계획 세우기

### Task
* 세진, 재영
- [x] 리뷰 전처리 중복되는거 
- [ ] 맞춤법 

* 희락
- [x] review text 에 이모티콘 변경없이 저장되도록 작업
  -  EC2 서버의 mysql 설정을 utf8mb4 로 바꿔줘서 해결! 👍 
- [x] DB 테스트

사용방법
  0. `chmod 777 main_crawling_{맡은번호}.sh crawling_{맡은번호}.sh` 실행권한부터 주세요!
  1. 각자 폴더의 위치와 폴더명이 다를 수 있으므로 그 부분을 수정해준다.
    - bash 폴더에 있는 crawling_{맡은번호}.sh 를 들어가보면 아래와 같이 나올거에요
      ![image](https://user-images.githubusercontent.com/52475378/145760945-184339c0-8582-485c-901a-1f7bd4641362.png)
    - 저는 `/opt/ml/final_project` 이 위치에 new_review_crawling.py 파일이 있어서 `cd` 를 통해서 폴더위치로 이동했어요
    - 실행할때의 현재 위치에 따라서 폴더를 찾고 못찾고 할 수 있으니 꼭 변경해주셔야 합니다.
    - 그 다음은 python3 하고 뒤에 실행하는 부분에서도 폴더위치 동일하게 수정해주세요!
  2. 각자 맡은 번호의 main_crawling_{맡은번호}.sh 파일을 수정한다.  
    ![image](https://user-images.githubusercontent.com/52475378/145761143-73d00f00-2099-4281-8d9b-a1c4e5f42aac.png)
    - 여기도 mkdir 부분이나 밑에 echo 하고 "" 안에 적힌 부분 모두 폴더명 자기의 셋팅환경에 맞춰서 수정해주세요
  3. 마지막으로 main_crawling_{맡은번호}.sh 실행해주세요
    ex) 1번이 맡은 번호라면 `bash main_crawling_1.sh` 
  4. `crontab -l` 을 실행해서 잘 등록됐는지 확인해주세요
    ![image](https://user-images.githubusercontent.com/52475378/145768901-89e6df76-1103-444a-83c4-2565b4d254ad.png)

이렇게 하고 나면 새벽 2시에 자동으로 크롤링이 실행될거에요 그리고 log 파일이 쌓일건데 다음날 안쌓인 분은 얘기해주세요
